<a href="https://colab.research.google.com/github/ayushtiwari4122/Ayush_python/blob/main/12_march_to_19_march.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#1 -> Wrtie statement to import numpy ?
import numpy as nm

In [ ]:
#2 -> Create an array using Numpy ?
a = [1,2,3,4,5,6]
nm.array(a)

array([1, 2, 3, 4, 5, 6])

In [ ]:
#3 -> Create an array of 10 random variables ?
b = nm.random.randint(1,30,10)
print(b)

[ 3 19 12 11  4 22 14 14 19 20]


In [ ]:
#4 -> Create an array of elements from 10-20 ?
c = nm.arange(10,20)
print(c)

[10 11 12 13 14 15 16 17 18 19]


In [ ]:
#5 -> Create an array which contains value 5, 10 times ?
d = nm.array([5]*10)
print(d)

[5 5 5 5 5 5 5 5 5 5]


In [ ]:
#6 -> Create a one dimensional array and convert it into 3*3 matrix ?
e = nm.array([1,2,3,4,5,6,7,8,9])
f = e.reshape(3,3)
print(f)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#8 -> Concatenate 2D array horizontally and vertically ?
g = nm.arange(1,10).reshape(3,3)
h = nm.arange(11,20).reshape(3,3)

l = nm.vstack([g,h])
print(l)

x = nm.hstack([g,h])
print(x)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]
[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]


In [ ]:
#7 -> Create a 2D array of size 3*3 but all the elements should be between 0 to 1 ?
j = nm.random.rand(9).reshape(3,3)
print(j)



NameError: name 'nm' is not defined

In [ ]:
### 12/03
import pandas as pd

In [ ]:
df = pd.read_csv("/content/covid_toy - covid_toy.csv")
df

,age,gender,fever,cough,city,has_covid
0,60,Male,103.0,Mild,Kolkata,No
1,27,Male,100.0,Mild,Delhi,Yes
2,42,Male,101.0,Mild,Delhi,No
3,31,Female,98.0,Mild,Kolkata,No
4,65,Female,101.0,Mild,Mumbai,No
...,...,...,...,...,...,...
95,12,Female,104.0,Mild,Bangalore,No
96,51,Female,101.0,Strong,Kolkata,Yes
97,20,Female,101.0,Mild,Bangalore,No
98,5,Female,98.0,Strong,Mumbai,No


In [ ]:
### Top Data Check, we will use df.head() and by Default it returns top 5 rows.
df.head(2)

,age,gender,fever,cough,city,has_covid
0,60,Male,103.0,Mild,Kolkata,No
1,27,Male,100.0,Mild,Delhi,Yes


In [ ]:
### Bottom Data Check, we will use df.tail(0) and by Default it returns bottom 5 rows.
df.tail(3)

,age,gender,fever,cough,city,has_covid
97,20,Female,101.0,Mild,Bangalore,No
98,5,Female,98.0,Strong,Mumbai,No
99,10,Female,98.0,Strong,Kolkata,Yes


In [ ]:
### If you want random indexed data, then we will use df.sample() and by default it returns a SINGLE row.
df.sample()

,age,gender,fever,cough,city,has_covid
35,82,Female,102.0,Strong,Bangalore,No


In [ ]:
### If we want to check data type of each column, we use df.dtypes.
df.dtypes

,0
age,int64
gender,object
fever,float64
cough,object
city,object
has_covid,object


In [ ]:
### If we want to check overall information then we will use df.info()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   age        100 non-null    int64  
 1   gender     100 non-null    object 
 2   fever      90 non-null     float64
 3   cough      100 non-null    object 
 4   city       100 non-null    object 
 5   has_covid  100 non-null    object 
dtypes: float64(1), int64(1), object(4)
memory usage: 4.8+ KB


In [ ]:
# x = 100
# # 50% = 50
#  x =1,2,3,4,5
#  mean = (1+2+3+4+5)/5 = 15/5 = 3


In [ ]:
### If you want to check Statical View of data, then we use df.describe()
df.describe()

,age,fever
count,100.000000,90.000000
mean,44.220000,100.844444
std,24.878931,2.054926
min,5.000000,98.000000
25%,20.000000,99.000000
50%,45.000000,101.000000
75%,66.500000,102.750000
max,84.000000,104.000000


In [ ]:
df.head(2)

,age,gender,fever,cough,city,has_covid
0,60,Male,103.0,Mild,Kolkata,No
1,27,Male,100.0,Mild,Delhi,Yes


In [ ]:
### IF you want to check missing data in a df, then we will use df.isnull().sum()
df.isnull().sum()  ### here fever has 10 missing values.

,0
age,0
gender,0
fever,10
cough,0
city,0
has_covid,0


In [ ]:
# x = 1,2,3,Nan,5
#  mean = (1+2+3+5)/4 = 11/4 =2.75
# we will fill this mean value in the missing values/data.
# x = 1,2,3,2.75,5

In [ ]:
df['fever'] = df['fever'].fillna(df['fever'].mean())

In [ ]:
df.isnull().sum()

,0
age,0
gender,0
fever,0
cough,0
city,0
has_covid,0


In [ ]:
df.head(1)

,age,gender,fever,cough,city,has_covid
0,60,Male,103.0,Mild,Kolkata,No


In [ ]:
### IF you have Categorical Data and you want to check Total Sub-categories then
# We will use df['column_name'].value_counts()
df['gender'].value_counts()

,count
gender,
Female,59
Male,41


In [ ]:
### If we want to replace the Categorical data with numbers then
# we use df['column_name'] = df['gender'].map({'Female':1,"Male":0})

In [ ]:
df['gender']
df.head(5)

,age,gender,fever,cough,city,has_covid
0,60,Male,103.0,Mild,Kolkata,No
1,27,Male,100.0,Mild,Delhi,Yes
2,42,Male,101.0,Mild,Delhi,No
3,31,Female,98.0,Mild,Kolkata,No
4,65,Female,101.0,Mild,Mumbai,No


In [ ]:
df['cough'] = df['cough'].map({'mild':0,"strong":1})
df.head(5)

,age,gender,fever,cough,city,has_covid
0,60,Male,103.0,NaN,Kolkata,No
1,27,Male,100.0,NaN,Delhi,Yes
2,42,Male,101.0,NaN,Delhi,No
3,31,Female,98.0,NaN,Kolkata,No
4,65,Female,101.0,NaN,Mumbai,No


In [ ]:
##city
df["city"].value_counts()

,count
city,
Kolkata,32
Bangalore,30
Delhi,22
Mumbai,16


In [ ]:
df["city"] = df['city'].map({'Kolkata':1, "Bangalore":2, "Delhi":3, "Mumbai":4})
df

,age,gender,fever,cough,city,has_covid
0,60,Male,103.0,NaN,1,No
1,27,Male,100.0,NaN,3,Yes
2,42,Male,101.0,NaN,3,No
3,31,Female,98.0,NaN,1,No
4,65,Female,101.0,NaN,4,No
...,...,...,...,...,...,...
95,12,Female,104.0,NaN,2,No
96,51,Female,101.0,NaN,1,Yes
97,20,Female,101.0,NaN,2,No
98,5,Female,98.0,NaN,4,No


In [ ]:
# 19/03
import pandas as pd
df = pd.read_csv("/content/placement - placement.csv")
df

,cgpa,resume_score,placed
0,8.14,6.52,1
1,6.17,5.17,0
2,8.27,8.86,1
3,6.88,7.27,1
4,7.52,7.30,1
...,...,...,...
95,6.33,6.38,0
96,8.23,7.76,1
97,6.65,7.78,0
98,8.14,5.63,1


In [ ]:
# s = df.filter(items = [5,6], axis = 0) ### axis

In [ ]:
s = df.to_dict()   ### to save data in dictionary manner -> export data in dictionary
s

{'cgpa': {0: 8.14,
  1: 6.17,
  2: 8.27,
  3: 6.88,
  4: 7.52,
  5: 8.77,
  6: 5.34,
  7: 6.56,
  8: 6.32,
  9: 7.69,
  10: 6.18,
  11: 5.44,
  12: 6.09,
  13: 8.5,
  14: 7.51,
  15: 8.88,
  16: 8.04,
  17: 7.81,
  18: 5.94,
  19: 6.75,
  20: 5.8,
  21: 6.53,
  22: 6.16,
  23: 6.05,
  24: 8.22,
  25: 7.76,
  26: 6.27,
  27: 5.51,
  28: 7.46,
  29: 6.19,
  30: 7.36,
  31: 5.92,
  32: 5.87,
  33: 8.43,
  34: 8.87,
  35: 8.07,
  36: 8.16,
  37: 9.05,
  38: 6.0,
  39: 7.5,
  40: 8.25,
  41: 8.68,
  42: 6.9,
  43: 8.21,
  44: 5.47,
  45: 8.1,
  46: 5.83,
  47: 7.05,
  48: 5.54,
  49: 5.46,
  50: 8.22,
  51: 6.54,
  52: 5.9,
  53: 6.0,
  54: 5.92,
  55: 6.94,
  56: 6.13,
  57: 6.34,
  58: 6.47,
  59: 5.95,
  60: 5.87,
  61: 6.89,
  62: 5.75,
  63: 8.65,
  64: 7.93,
  65: 6.04,
  66: 8.35,
  67: 6.59,
  68: 6.01,
  69: 8.06,
  70: 7.12,
  71: 7.34,
  72: 7.63,
  73: 5.76,
  74: 5.54,
  75: 6.34,
  76: 9.4,
  77: 5.88,
  78: 5.79,
  79: 5.27,
  80: 7.83,
  81: 6.12,
  82: 7.92,
  83: 7.6,
  84

In [ ]:
q = df.to_string()   ### to export or save data in string manner
q

'    cgpa  resume_score  placed\n0   8.14          6.52       1\n1   6.17          5.17       0\n2   8.27          8.86       1\n3   6.88          7.27       1\n4   7.52          7.30       1\n5   8.77          6.19       1\n6   5.34          7.09       0\n7   6.56          6.29       0\n8   6.32          6.71       0\n9   7.69          7.12       1\n10  6.18          6.35       0\n11  5.44          6.54       0\n12  6.09          7.01       0\n13  8.50          5.09       1\n14  7.51          6.25       1\n15  8.88          5.93       1\n16  8.04          7.64       1\n17  7.81          8.71       1\n18  5.94          5.88       0\n19  6.75          8.11       1\n20  5.80          8.06       0\n21  6.53          7.64       0\n22  6.16          5.77       0\n23  6.05          7.13       0\n24  8.22          6.18       1\n25  7.76          5.68       1\n26  6.27          6.47       0\n27  5.51          6.15       0\n28  7.46          7.67       1\n29  6.19          7.30       0\n30  7.3

In [ ]:
e = df.to_csv("path_;ocation")    ### to export or save data in csv manner

In [ ]:
idx = df.columns
idx

Index(['cgpa', 'resume_score', 'placed'], dtype='object')

In [ ]:
label = df.columns[0]   ### to get the column by giving its index

In [ ]:
q = df.columns.values     ### array of column labels
q

array(['cgpa', 'resume_score', 'placed'], dtype=object)

In [ ]:
p = df.copy()
p = df.rename(columns = {'cgpa':'updated_cgpa',
                         'resume_score':'semester_marks'})    ### how to rename a colummn
p

,updated_cgpa,semester_marks,placed
0,8.14,6.52,1
1,6.17,5.17,0
2,8.27,8.86,1
3,6.88,7.27,1
4,7.52,7.30,1
...,...,...,...
95,6.33,6.38,0
96,8.23,7.76,1
97,6.65,7.78,0
98,8.14,5.63,1


In [ ]:
df['half'] = df['cgpa'].where(df['cgpa']>7,other = 0)   ### where -> it is used to extract out that data which satisfy the given conditioon.
df.head(10)

,cgpa,resume_score,placed,half
0,8.14,6.52,1,8.14
1,6.17,5.17,0,0.00
2,8.27,8.86,1,8.27
3,6.88,7.27,1,0.00
4,7.52,7.30,1,7.52
5,8.77,6.19,1,8.77
6,5.34,7.09,0,0.00
7,6.56,6.29,0,0.00
8,6.32,6.71,0,0.00
9,7.69,7.12,1,7.69


In [ ]:
tip = pd.read_csv("/content/tips - tips.csv")
tip

,total_bill,tip,sex,smoker,day,time,size
0,16.99,1.01,Female,No,Sun,Dinner,2
1,10.34,1.66,Male,No,Sun,Dinner,3
2,21.01,3.50,Male,No,Sun,Dinner,3
3,23.68,3.31,Male,No,Sun,Dinner,2
4,24.59,3.61,Female,No,Sun,Dinner,4
...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3
240,27.18,2.00,Female,Yes,Sat,Dinner,2
241,22.67,2.00,Male,Yes,Sat,Dinner,2
242,17.82,1.75,Male,No,Sat,Dinner,2


In [ ]:
tips = tip.copy()
tips = tip.filter(items = [11,13], axis = 0)
tips.rename(columns = {'sex': 'Gender',
                      'size':'Serving'})
tips["Male Customers"] = tips['sex'].where(tips['sex']=="Male", other = 0)
col




,total_bill,tip,sex,smoker,day,time,size,Male Customers
11,35.26,5.0,Female,No,Sun,Dinner,4,0
13,18.43,3.0,Male,No,Sun,Dinner,4,Male


In [ ]:
# DATA --
#  (1). Numerical ---> Continous Data ---> we can divide furthur.
# Ex: Salary --> 20500.60, weight = 70.54, distance = 270.65,height,age,etc
#  Koi bhi essaa data jo apne se choti measurement value m divide ho skta h then uss type ka data Numerical Data

#  (2). Categorical ---> Discrete Data ---> we cannot divide this type data further.

#  Ex: Gender(M,F), Martial Status(M,U), Number of employees in officce
#  Jo bhi data value ya data info jisko hum ussse kisi bhi choti measurement unit m agr ni divide kr skte to wo categorical data h